const SUBCOMMENT_PATH = '/subcomment/';

export const GET_BY_COMMENT_ID_PATH = SUBCOMMENT_PATH;
export const ADD_SUB_COMMENT_PATH = SUBCOMMENT_PATH;
export const UPDATE_SUB_COMMENT_PATH = SUBCOMMENT_PATH;